package com.mgd.painmapp.model.database

data class CSVTable (
    val idEvaluation: Long,
    val patient: String,
    val researcher: String,
    val date: String,
    val test: String,
    val idMap: Long,
    val pathsDrawnFront: String,
    val pathsDrawnBack: String,
    val totalPercentage: Float,
    val rightPercentage: Float,
    val leftPercentage: Float,
    var nervioMedianoDerecho : Float,
    var nervioRadialSuperficialDerecho : Float,
    var nervioCubitalDerecho : Float,
    var nervioMusculoCutaneoDerecho : Float,
    var nerviosSupraclavicularesDerechos : Float,
    var nervioFemoralDerecho : Float,
    var nervioGenitalDerecho : Float,
    var nervioIlioinguinoDerecho : Float,
    var nervioObturadoDerecho : Float,
    var nervioFemoralAnteriorDerecho: Float,
    var nervioSafenoDerecho : Float,
    var nervioPeroneoDerecho: Float,
    var nervioSuralDerecho : Float,
    var nervioBraquialDerecho : Float,
    var nervioAntebrazoDerecho : Float,
    var nervioRadialDerecho : Float,
    var nervioAxilarDerecho: Float,
    var nervioMedianoIzquierdo : Float,
    var nervioRadialSuperficialIzquierdo : Float,
    var nervioCubitalIzquierdo : Float,
    var nervioMusculoCutaneoIzquierdo : Float,
    var nerviosSupraclavicularesIzquierdos : Float,
    var nervioFemoralIzquierdo : Float,
    var nervioGenitalIzquierdo : Float,
    var nervioIlioinguinoIzquierdo : Float,
    var nervioObturadoIzquierdo : Float,
    var nervioFemoralAnteriorIzquierdo : Float,
    var nervioSafenoIzquierdo : Float,
    var nervioPeroneoIzquierdo : Float,
    var nervioSuralIzquierdo : Float,
    var nervioBraquialIzquierdo : Float,
    var nervioAntebrazoIzquierdo: Float,
    var nervioRadialIzquierdo : Float,
    var nervioAxilarIzquierdo : Float,
    val idSymptom: Long,
    val intensity: Float,
    val symptom: String,
    val symptomOtherText: String,
    val charactAgitating: Boolean,
    val charactMiserable: Boolean,
    val charactAnnoying: Boolean,
    val charactUnbearable: Boolean,
    val charactFatiguing: Boolean,
    val charactPiercing: Boolean,
    val charactOther: Boolean,
    val charactOtherText: String,
    val timeContinuous: String,
    val timeWhen: String
)