package com.mgd.painmapp.model.database

data class MapInterpretation (
    var idEvaluation : Long,
    var pathsDrawnFront : String,
    var pathsDrawnBack : String,
    var totalPatientPercentage : Float?,
    var rightPatientPercentage : Float?,
    var leftPatientPercentage : Float?,
    var totalPercentage : Float,
    var rightPercentage : Float,
    var leftPercentage : Float,
    var nervioMedianoDerecho : Float,
    var nervioRadialSuperficialDerecho : Float,
    var nervioCubitalDerecho : Float,
    var nervioMusculocutaneoDerecho: Float,
    var nerviosSupraclavicularesDerechos : Float,
    var nervioFemorocutaneoLatDerecho : Float,
    var nervioGenitofemoralDerecho : Float,
    var nervioIlioinguinalDerecho : Float,
    var nervioIliohipogastricoDerecho : Float,
    var nervioObturadoDerecho : Float,
    var nervioCutaneofemoralAntDerecho : Float,
    var nervioSafenoDerecho : Float,
    var nervioPeroneoSuperfDerecho : Float,
    var nervioSuralDerecho : Float,
    var nervioBraquialDerecho : Float,
    var nervioAntebrazoDerecho : Float,
    var nervioRadialDerecho : Float,
    var nervioAxilarDerecho : Float,
    var nerviosCervicalesDerechos : Float,
    var nervioTrigeminoIDerecho : Float,
    var nervioTrigeminoIIDerecho : Float,
    var nervioTrigeminoIIIDerecho : Float,
    var T1Derecho : Float,
    var T2Derecho : Float,
    var T3Derecho : Float,
    var T4Derecho : Float,
    var T5Derecho : Float,
    var T6Derecho : Float,
    var T7Derecho : Float,
    var T8Derecho: Float,
    var T9Derecho : Float,
    var T10Derecho : Float,
    var T11Derecho : Float,
    var T12Derecho : Float,
    var nervioMedianoIzquierdo : Float,
    var nervioRadialSuperficialIzquierdo : Float,
    var nervioCubitalIzquierdo : Float,
    var nervioMusculocutaneoIzquierdo: Float,
    var nerviosSupraclavicularesIzquierdos : Float,
    var nervioFemorocutaneoLatIzquierdo : Float,
    var nervioGenitofemoralIzquierdo : Float,
    var nervioIlioinguinalIzquierdo : Float,
    var nervioIliohipogastricoIzquierdo : Float,
    var nervioObturadoIzquierdo: Float,
    var nervioCutaneofemoralAntIzquierdo : Float,
    var nervioSafenoIzquierdo : Float,
    var nervioPeroneoSuperfIzquierdo : Float,
    var nervioSuralIzquierdo : Float,
    var nervioBraquialIzquierdo : Float,
    var nervioAntebrazoIzquierdo : Float,
    var nervioRadialIzquierdo : Float,
    var nervioAxilarIzquierdo : Float,
    var nerviosCervicalesIzquierdo : Float,
    var nervioTrigeminoIIzquierdo : Float,
    var nervioTrigeminoIIIzquierdo : Float,
    var nervioTrigeminoIIIIzquierdo : Float,
    var T1Izquierdo : Float,
    var T2Izquierdo : Float,
    var T3Izquierdo : Float,
    var T4Izquierdo : Float,
    var T5Izquierdo: Float,
    var T6Izquierdo : Float,
    var T7Izquierdo : Float,
    var T8Izquierdo: Float,
    var T9Izquierdo : Float,
    var T10Izquierdo : Float,
    var T11Izquierdo : Float,
    var T12Izquierdo : Float
)