package com.mgd.painmapp.model.database

data class MapInterpretation (
    var idEvaluation : Long,
    var pathsDrawnFront : String,
    var pathsDrawnBack : String,
    var totalPatientPercentage : Float?,
    var rightPatientPercentage : Float?,
    var leftPatientPercentage : Float?,
    var totalPercentage : Float,
    var rightPercentage : Float,
    var leftPercentage : Float,
    var nervioMedianoDerecho : Float,
    var nervioRadialSuperficialDerecho : Float,
    var nervioCubitalDerecho : Float,
    var nervioMusculocutaneoDerecho: Float,
    var nerviosSupraclavicularesDerechos : Float,
    var nervioFemorocutaneoLatDerecho : Float,
    var nervioGenitofemoralDerecho : Float,
    var nervioIlioinguinalDerecho : Float,
    var nervioIliohipogastricoDerecho : Float,
    var nervioObturadoDerecho : Float,
    var nervioCutaneofemoralAntDerecho : Float,
    var nervioSafenoDerecho : Float,
    var nervioPeroneoSuperfDerecho : Float,
    var nervioSuralDerecho : Float,
    var nervioBraquialDerecho : Float,
    var nervioAntebrazoDerecho : Float,
    var nervioRadialDerecho : Float,
    var nervioAxilarDerecho : Float,
    var nerviosCervicalesDerechos : Float,
    var nervioTrigeminoIDerecho : Float,
    var nervioTrigeminoIIDerecho : Float,
    var nervioTrigeminoIIIDerecho : Float,
    var T1Derecho : Float,
    var T2Derecho : Float,
    var T3Derecho : Float,
    var T4Derecho : Float,
    var T5Derecho : Float,
    var T6Derecho : Float,
    var T7Derecho : Float,
    var T8Derecho: Float,
    var T9Derecho : Float,
    var T10Derecho : Float,
    var T11Derecho : Float,
    var T12Derecho : Float,
    var nervioMedianoIzquierdo : Float,
    var nervioRadialSuperficialIzquierdo : Float,
    var nervioCubitalIzquierdo : Float,
    var nervioMusculocutaneoIzquierdo: Float,
    var nerviosSupraclavicularesIzquierdos : Float,
    var nervioFemorocutaneoLatIzquierdo : Float,
    var nervioGenitofemoralIzquierdo : Float,
    var nervioIlioinguinalIzquierdo : Float,
    var nervioIliohipogastricoIzquierdo : Float,
    var nervioObturadoIzquierdo: Float,
    var nervioCutaneofemoralAntIzquierdo : Float,
    var nervioSafenoIzquierdo : Float,
    var nervioPeroneoSuperfIzquierdo : Float,
    var nervioSuralIzquierdo : Float,
    var nervioBraquialIzquierdo : Float,
    var nervioAntebrazoIzquierdo : Float,
    var nervioRadialIzquierdo : Float,
    var nervioAxilarIzquierdo : Float,
    var nerviosCervicalesIzquierdo : Float,
    var nervioTrigeminoIIzquierdo : Float,
    var nervioTrigeminoIIIzquierdo : Float,
    var nervioTrigeminoIIIIzquierdo : Float,
    var T1Izquierdo : Float,
    var T2Izquierdo : Float,
    var T3Izquierdo : Float,
    var T4Izquierdo : Float,
    var T5Izquierdo: Float,
    var T6Izquierdo : Float,
    var T7Izquierdo : Float,
    var T8Izquierdo: Float,
    var T9Izquierdo : Float,
    var T10Izquierdo : Float,
    var T11Izquierdo : Float,
    var T12Izquierdo : Float,
    var nervioCutAnteroBraqPostDerecho : Float,
    var nervioCutAnteroBraqPostIzquierdo : Float,
    var nervioCalcaneoDerecho : Float,
    var nervioCalcaneoIzquierdo : Float,
    var nervioPlantarLateralDerecho : Float,
    var  nervioPlantarLateralIzquierdo : Float,
    var  nervioCutFemoralPostDerecho : Float,
    var  nervioCutFemoralPostIzquierdo : Float,
    var nervioCluneosDerecho : Float,
    var nervioCluneosIzquierdo : Float,
    var L1Derecho : Float,
    var L1Izquierdo : Float,
    var L2Derecho : Float,
    var L2Izquierdo : Float,
    var SacrosDerecho : Float,
    var SacrosIzquierdo : Float,
    var nervioOccipitalMayorDerecho : Float,
    var nervioOccipitalMayorIzquierdo : Float,
    var nervioOccipitalMenorDerecho : Float,
    var nervioOccipitalMenorIzquierdo : Float,
    var nervioAuricularMayorDerecho: Float,
    var nervioAuricularMayorIzquierdo: Float,
    var nervioTransversoDerecho: Float,
    var nervioTransversoIzquierdo: Float,
    var nervioPlatarMedialDerecho: Float,
    var nervioPlatarMedialIzquierdo: Float,

    var RC3Derecha : Float,
    var RC4Derecha : Float,
    var RC5Derecha : Float,
    var RC6Derecha : Float,
    var RC7Derecha : Float,
    var RC8Derecha : Float,
    var RT1Derecha : Float,
    var RT2Derecha : Float,
    var RT3Derecha : Float,
    var RT4Derecha : Float,
    var RT5Derecha : Float,
    var RT6Derecha : Float,
    var RT7Derecha : Float,
    var RT8Derecha : Float,
    var RT9Derecha : Float,
    var RT10Derecha : Float,
    var RT11Derecha : Float,
    var RT12Derecha : Float,
    var RL1Derecha : Float,
    var RL2Derecha : Float,
    var RL3Derecha : Float,
    var RL4Derecha : Float,
    var RL5Derecha : Float,
    var RS1Derecha : Float,
    var RS2Derecha : Float,
    var RC3Izquierda : Float,
    var RC4Izquierda : Float,
    var RC5Izquierda : Float,
    var RC6Izquierda : Float,
    var RC7Izquierda : Float,
    var RC8Izquierda : Float,
    var RT1Izquierda : Float,
    var RT2Izquierda : Float,
    var RT3Izquierda : Float,
    var RT4Izquierda : Float,
    var RT5Izquierda : Float,
    var RT6Izquierda : Float,
    var RT7Izquierda : Float,
    var RT8Izquierda : Float,
    var RT9Izquierda : Float,
    var RT10Izquierda : Float,
    var RT11Izquierda : Float,
    var RT12Izquierda : Float,
    var RL1Izquierda : Float,
    var RL2Izquierda : Float,
    var RL3Izquierda : Float,
    var RL4Izquierda : Float,
    var RL5Izquierda : Float,
    var RS1Izquierda : Float,
    var RS2Izquierda : Float
)