package com.mgd.painmapp.model.database

data class MapInterpretation (
    var idEvaluation : Long,
    var pathsDrawnFront : String,
    var pathsDrawnBack : String,
    var totalPatientPercentage : Float?,
    var rightPatientPercentage : Float?,
    var leftPatientPercentage : Float?,
    var totalPercentage : Float,
    var rightPercentage : Float,
    var leftPercentage : Float,
    var nervioMedianoDerecho : Float,
    var nervioRadialSuperficialDerecho : Float,
    var nervioCubitalDerecho : Float,
    var nervioMusculoCutaneoDerecho : Float,
    var nerviosSupraclavicularesDerechos : Float,
    var nervioFemoralDerecho : Float,
    var nervioGenitalDerecho : Float,
    var nervioIlioinguinoDerecho : Float,
    var nervioObturadoDerecho : Float,
    var nervioFemoralAnteriorDerecho: Float,
    var nervioSafenoDerecho : Float,
    var nervioPeroneoDerecho: Float,
    var nervioSuralDerecho : Float,
    var nervioBraquialDerecho : Float,
    var nervioAntebrazoDerecho : Float,
    var nervioRadialDerecho : Float,
    var nervioAxilarDerecho: Float,
    var nervioMedianoIzquierdo : Float,
    var nervioRadialSuperficialIzquierdo : Float,
    var nervioCubitalIzquierdo : Float,
    var nervioMusculoCutaneoIzquierdo : Float,
    var nerviosSupraclavicularesIzquierdos : Float,
    var nervioFemoralIzquierdo : Float,
    var nervioGenitalIzquierdo : Float,
    var nervioIlioinguinoIzquierdo : Float,
    var nervioObturadoIzquierdo : Float,
    var nervioFemoralAnteriorIzquierdo : Float,
    var nervioSafenoIzquierdo : Float,
    var nervioPeroneoIzquierdo : Float,
    var nervioSuralIzquierdo : Float,
    var nervioBraquialIzquierdo : Float,
    var nervioAntebrazoIzquierdo: Float,
    var nervioRadialIzquierdo : Float,
    var nervioAxilarIzquierdo : Float
)