package com.mgd.painmapp.model.database

data class NervesTable (
    val symptom: String, //para mostrar la afectación nerviosa por síntoma
    val nervioMedianoDerecho : Float,
    val nervioRadialSuperficialDerecho : Float,
    val nervioCubitalDerecho : Float,
    val nervioMusculoCutaneoDerecho : Float,
    val nerviosSupraclavicularesDerechos : Float,
    val nervioFemoralDerecho : Float,
    val nervioGenitalDerecho : Float,
    val nervioIlioinguinoDerecho : Float,
    val nervioObturadoDerecho : Float,
    val nervioFemoralAnteriorDerecho: Float,
    val nervioSafenoDerecho : Float,
    val nervioPeroneoDerecho: Float,
    val nervioSuralDerecho : Float,
    val nervioBraquialDerecho : Float,
    val nervioAntebrazoDerecho : Float,
    val nervioRadialDerecho : Float,
    val nervioAxilarDerecho: Float,
    val nervioMedianoIzquierdo : Float,
    val nervioRadialSuperficialIzquierdo : Float,
    val nervioCubitalIzquierdo : Float,
    val nervioMusculoCutaneoIzquierdo : Float,
    val nerviosSupraclavicularesIzquierdos : Float,
    val nervioFemoralIzquierdo : Float,
    val nervioGenitalIzquierdo : Float,
    val nervioIlioinguinoIzquierdo : Float,
    val nervioObturadoIzquierdo : Float,
    val nervioFemoralAnteriorIzquierdo : Float,
    val nervioSafenoIzquierdo : Float,
    val nervioPeroneoIzquierdo : Float,
    val nervioSuralIzquierdo : Float,
    val nervioBraquialIzquierdo : Float,
    val nervioAntebrazoIzquierdo: Float,
    val nervioRadialIzquierdo : Float,
    val nervioAxilarIzquierdo : Float
)