package com.mgd.painmapp.model.database

data class NervesTable (
    val symptom: String, //para mostrar la afectación nerviosa por síntoma
    val symptomOtherText: String,
    val nervioMedianoDerecho: Float,
    val nervioRadialSuperficialDerecho: Float,
    val nervioCubitalDerecho: Float,
    val nervioMusculocutaneoDerecho: Float,
    val nerviosSupraclavicularesDerechos: Float,
    val nervioFemorocutaneoLatDerecho: Float,
    val nervioGenitofemoralDerecho: Float,
    val nervioIlioinguinalDerecho: Float,
    val nervioIliohipogastricoDerecho: Float,
    val nervioObturadoDerecho: Float,
    val nervioCutaneofemoralAntDerecho: Float,
    val nervioSafenoDerecho: Float,
    val nervioPeroneoSuperfDerecho: Float,
    val nervioSuralDerecho: Float,
    val nervioBraquialDerecho: Float,
    val nervioAntebrazoDerecho: Float,
    val nervioRadialDerecho: Float,
    val nervioAxilarDerecho: Float,
    val nerviosCervicalesDerechos: Float,
    val nervioTrigeminoIDerecho: Float,
    val nervioTrigeminoIIDerecho: Float,
    val nervioTrigeminoIIIDerecho: Float,
    val T1Derecho: Float,
    val T2Derecho: Float,
    val T3Derecho: Float,
    val T4Derecho: Float,
    val T5Derecho: Float,
    val T6Derecho: Float,
    val T7Derecho: Float,
    val T8Derecho: Float,
    val T9Derecho: Float,
    val T10Derecho: Float,
    val T11Derecho: Float,
    val T12Derecho: Float,
    val nervioMedianoIzquierdo: Float,
    val nervioRadialSuperficialIzquierdo: Float,
    val nervioCubitalIzquierdo: Float,
    val nervioMusculocutaneoIzquierdo: Float,
    val nerviosSupraclavicularesIzquierdos: Float,
    val nervioFemorocutaneoLatIzquierdo: Float,
    val nervioGenitofemoralIzquierdo: Float,
    val nervioIlioinguinalIzquierdo: Float,
    val nervioIliohipogastricoIzquierdo: Float,
    val nervioObturadoIzquierdo: Float,
    val nervioCutaneofemoralAntIzquierdo: Float,
    val nervioSafenoIzquierdo: Float,
    val nervioPeroneoSuperfIzquierdo: Float,
    val nervioSuralIzquierdo: Float,
    val nervioBraquialIzquierdo: Float,
    val nervioAntebrazoIzquierdo: Float,
    val nervioRadialIzquierdo: Float,
    val nervioAxilarIzquierdo: Float,
    val nerviosCervicalesIzquierdo: Float,
    val nervioTrigeminoIIzquierdo: Float,
    val nervioTrigeminoIIIzquierdo: Float,
    val nervioTrigeminoIIIIzquierdo: Float,
    val T1Izquierdo: Float,
    val T2Izquierdo: Float,
    val T3Izquierdo: Float,
    val T4Izquierdo: Float,
    val T5Izquierdo: Float,
    val T6Izquierdo: Float,
    val T7Izquierdo: Float,
    val T8Izquierdo: Float,
    val T9Izquierdo: Float,
    val T10Izquierdo: Float,
    val T11Izquierdo: Float,
    val T12Izquierdo: Float,
    var nervioCutAnteroBraqPostDerecho : Float,
    var nervioCutAnteroBraqPostIzquierdo : Float,
    var nervioCalcaneoDerecho : Float,
    var nervioCalcaneoIzquierdo : Float,
    var nervioPlantarLateralDerecho : Float,
    var  nervioPlantarLateralIzquierdo : Float,
    var  nervioCutFemoralPostDerecho : Float,
    var  nervioCutFemoralPostIzquierdo : Float,
    var nervioCluneosDerecho : Float,
    var nervioCluneosIzquierdo : Float,
    var L1Derecho : Float,
    var L1Izquierdo : Float,
    var  L2Derecho : Float,
    var  L2Izquierdo : Float,
    var  SacrosDerecho : Float,
    var  SacrosIzquierdo : Float,
    var  nervioOccipitalMayorDerecho : Float,
    var  nervioOccipitalMayorIzquierdo : Float,
    var  nervioOccipitalMenorDerecho : Float,
    var  nervioOccipitalMenorIzquierdo : Float,
    var  nervioAuricularMayorDerecho: Float,
    var  nervioAuricularMayorIzquierdo: Float,
    var  nervioTransversoDerecho: Float,
    var  nervioTransversoIzquierdo: Float,
    var nervioPlatarMedialDerecho: Float,
    var nervioPlatarMedialIzquierdo: Float,

    var RC3Derecha : Float,
    var RC4Derecha : Float,
    var RC5Derecha : Float,
    var RC6Derecha : Float,
    var RC7Derecha : Float,
    var RC8Derecha : Float,
    var RT1Derecha : Float,
    var RT2Derecha : Float,
    var RT3Derecha : Float,
    var RT4Derecha : Float,
    var RT5Derecha : Float,
    var RT6Derecha : Float,
    var RT7Derecha : Float,
    var RT8Derecha : Float,
    var RT9Derecha : Float,
    var RT10Derecha : Float,
    var RT11Derecha : Float,
    var RT12Derecha : Float,
    var RL1Derecha : Float,
    var RL2Derecha : Float,
    var RL3Derecha : Float,
    var RL4Derecha : Float,
    var RL5Derecha : Float,
    var RS1Derecha : Float,
    var RS2Derecha : Float,
    var RC3Izquierda : Float,
    var RC4Izquierda : Float,
    var RC5Izquierda : Float,
    var RC6Izquierda : Float,
    var RC7Izquierda : Float,
    var RC8Izquierda : Float,
    var RT1Izquierda : Float,
    var RT2Izquierda : Float,
    var RT3Izquierda : Float,
    var RT4Izquierda : Float,
    var RT5Izquierda : Float,
    var RT6Izquierda : Float,
    var RT7Izquierda : Float,
    var RT8Izquierda : Float,
    var RT9Izquierda : Float,
    var RT10Izquierda : Float,
    var RT11Izquierda : Float,
    var RT12Izquierda : Float,
    var RL1Izquierda : Float,
    var RL2Izquierda : Float,
    var RL3Izquierda : Float,
    var RL4Izquierda : Float,
    var RL5Izquierda : Float,
    var RS1Izquierda : Float,
    var RS2Izquierda : Float
)