package com.mgd.painmapp.model.database.entities

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import com.mgd.painmapp.model.database.MapInterpretation

@Entity(tableName="map_table")
data class MapEntity (
    @PrimaryKey(autoGenerate = true) @ColumnInfo(name="idMap") val idMap: Long = 0,
    @ColumnInfo(name="idEvaluation") val idEvaluation:Long,
    @ColumnInfo(name="pathsDrawnFront") val pathsDrawnFront: String,
    @ColumnInfo(name="pathsDrawnBack") val pathsDrawnBack: String,
    @ColumnInfo(name="totalPercentage") val totalPercentage:Float,
    @ColumnInfo(name="rightPercentage") val rightPercentage:Float,
    @ColumnInfo(name="leftPercentage") val leftPercentage:Float,
    @ColumnInfo(name="nervioMedianoDerecho") val nervioMedianoDerecho:Float,
    @ColumnInfo(name="nervioRadialSuperficialDerecho") val nervioRadialSuperficialDerecho:Float,
    @ColumnInfo(name="nervioMusculoCutaneoDerecho") val nervioMusculoCutaneoDerecho:Float,
    @ColumnInfo(name="nerviosSupraclavicularesDerechos") val nerviosSupraclavicularesDerechos:Float,
    @ColumnInfo(name="nervioFemoralDerecho") val nervioFemoralDerecho:Float,
    @ColumnInfo(name="nervioGenitalDerecho") val nervioGenitalDerecho:Float,
    @ColumnInfo(name="nervioIlioinguinoDerecho") val nervioIlioinguinoDerecho:Float,
    @ColumnInfo(name="nervioObturadoDerecho") val nervioObturadoDerecho:Float,
    @ColumnInfo(name="nervioFemoralAnteriorDerecho") val nervioFemoralAnteriorDerecho:Float,
    @ColumnInfo(name="nervioPeroneoDerecho") val nervioPeroneoDerecho:Float,
    @ColumnInfo(name="nervioSuralDerecho") val nervioSuralDerecho:Float,
    @ColumnInfo(name="nervioBraquialDerecho") val nervioBraquialDerecho:Float,
    @ColumnInfo(name="nervioAntebrazoDerecho") val nervioAntebrazoDerecho:Float,
    @ColumnInfo(name="nervioRadialDerecho") val nervioRadialDerecho:Float,
    @ColumnInfo(name="nervioAxilarDerecho") val nervioAxilarDerecho:Float,
    @ColumnInfo(name="nervioMedianoIzquierdo") val nervioMedianoIzquierdo:Float,
    @ColumnInfo(name="nervioRadialSuperficialIzquierdo") val nervioRadialSuperficialIzquierdo:Float,
    @ColumnInfo(name="nervioMusculoCutaneoIzquierdo") val nervioMusculoCutaneoIzquierdo:Float,
    @ColumnInfo(name="nerviosSupraclavicularesIzquierdos") val nerviosSupraclavicularesIzquierdos:Float,
    @ColumnInfo(name="nervioFemoralIzquierdo") val nervioFemoralIzquierdo:Float,
    @ColumnInfo(name="nervioGenitalIzquierdo") val nervioGenitalIzquierdo:Float,
    @ColumnInfo(name="nervioIlioinguinoIzquierdo") val nervioIlioinguinoIzquierdo:Float,
    @ColumnInfo(name="nervioObturadoIzquierdo") val nervioObturadoIzquierdo:Float,
    @ColumnInfo(name="nervioFemoralAnteriorIzquierdo") val nervioFemoralAnteriorIzquierdo:Float,
    @ColumnInfo(name="nervioPeroneoIzquierdo") val nervioPeroneoIzquierdo:Float,
    @ColumnInfo(name="nervioSuralIzquierdo") val nervioSuralIzquierdo:Float,
    @ColumnInfo(name="nervioBraquialIzquierdo") val nervioBraquialIzquierdo:Float,
    @ColumnInfo(name="nervioAntebrazoIzquierdo") val nervioAntebrazoIzquierdo:Float,
    @ColumnInfo(name="nervioRadialIzquierdo") val nervioRadialIzquierdo:Float,
    @ColumnInfo(name="nervioAxilarIzquierdo") val nervioAxilarIzquierdo:Float,

)

fun MapInterpretation.toDatabase() = MapEntity(
    idEvaluation = idEvaluation,
    pathsDrawnFront = pathsDrawnFront,
    pathsDrawnBack = pathsDrawnBack,
    totalPercentage = totalPercentage,
    rightPercentage = rightPercentage,
    leftPercentage = leftPercentage,
    nervioMedianoDerecho = nervioMedianoDerecho,
    nervioRadialSuperficialDerecho = nervioRadialSuperficialDerecho,
    nervioMusculoCutaneoDerecho = nervioMusculoCutaneoDerecho,
    nerviosSupraclavicularesDerechos = nerviosSupraclavicularesDerechos,
    nervioFemoralDerecho = nervioFemoralDerecho,
    nervioGenitalDerecho = nervioGenitalDerecho,
    nervioIlioinguinoDerecho = nervioIlioinguinoDerecho,
    nervioObturadoDerecho = nervioObturadoDerecho,
    nervioFemoralAnteriorDerecho = nervioFemoralAnteriorDerecho,
    nervioPeroneoDerecho = nervioPeroneoDerecho,
    nervioSuralDerecho = nervioSuralDerecho,
    nervioBraquialDerecho = nervioBraquialDerecho,
    nervioAntebrazoDerecho = nervioAntebrazoDerecho,
    nervioRadialDerecho = nervioRadialDerecho,
    nervioAxilarDerecho = nervioAxilarDerecho,
    nervioMedianoIzquierdo = nervioMedianoIzquierdo,
    nervioRadialSuperficialIzquierdo = nervioRadialSuperficialIzquierdo,
    nervioMusculoCutaneoIzquierdo = nervioMusculoCutaneoIzquierdo,
    nerviosSupraclavicularesIzquierdos = nerviosSupraclavicularesIzquierdos,
    nervioFemoralIzquierdo = nervioFemoralIzquierdo,
    nervioGenitalIzquierdo = nervioGenitalIzquierdo,
    nervioIlioinguinoIzquierdo = nervioIlioinguinoIzquierdo,
    nervioObturadoIzquierdo = nervioObturadoIzquierdo,
    nervioFemoralAnteriorIzquierdo = nervioFemoralAnteriorIzquierdo,
    nervioPeroneoIzquierdo = nervioPeroneoIzquierdo,
    nervioSuralIzquierdo = nervioSuralIzquierdo,
    nervioBraquialIzquierdo = nervioBraquialIzquierdo,
    nervioAntebrazoIzquierdo = nervioAntebrazoIzquierdo,
    nervioRadialIzquierdo = nervioRadialIzquierdo,
    nervioAxilarIzquierdo = nervioAxilarIzquierdo
)
fun MapEntity.toMapInterpretation() = MapInterpretation(
    idEvaluation = idEvaluation,
    pathsDrawnFront = pathsDrawnFront,
    pathsDrawnBack = pathsDrawnBack,
    totalPercentage = totalPercentage,
    rightPercentage = rightPercentage,
    leftPercentage = leftPercentage,
    nervioMedianoDerecho = nervioMedianoDerecho,
    nervioRadialSuperficialDerecho = nervioRadialSuperficialDerecho,
    nervioMusculoCutaneoDerecho = nervioMusculoCutaneoDerecho,
    nerviosSupraclavicularesDerechos = nerviosSupraclavicularesDerechos,
    nervioFemoralDerecho = nervioFemoralDerecho,
    nervioGenitalDerecho = nervioGenitalDerecho,
    nervioIlioinguinoDerecho = nervioIlioinguinoDerecho,
    nervioObturadoDerecho = nervioObturadoDerecho,
    nervioFemoralAnteriorDerecho = nervioFemoralAnteriorDerecho,
    nervioPeroneoDerecho = nervioPeroneoDerecho,
    nervioSuralDerecho = nervioSuralDerecho,
    nervioBraquialDerecho = nervioBraquialDerecho,
    nervioAntebrazoDerecho = nervioAntebrazoDerecho,
    nervioRadialDerecho = nervioRadialDerecho,
    nervioAxilarDerecho = nervioAxilarDerecho,
    nervioMedianoIzquierdo = nervioMedianoIzquierdo,
    nervioRadialSuperficialIzquierdo = nervioRadialSuperficialIzquierdo,
    nervioMusculoCutaneoIzquierdo = nervioMusculoCutaneoIzquierdo,
    nerviosSupraclavicularesIzquierdos = nerviosSupraclavicularesIzquierdos,
    nervioFemoralIzquierdo = nervioFemoralIzquierdo,
    nervioGenitalIzquierdo = nervioGenitalIzquierdo,
    nervioIlioinguinoIzquierdo = nervioIlioinguinoIzquierdo,
    nervioObturadoIzquierdo = nervioObturadoIzquierdo,
    nervioFemoralAnteriorIzquierdo = nervioFemoralAnteriorIzquierdo,
    nervioPeroneoIzquierdo = nervioPeroneoIzquierdo,
    nervioSuralIzquierdo = nervioSuralIzquierdo,
    nervioBraquialIzquierdo = nervioBraquialIzquierdo,
    nervioAntebrazoIzquierdo = nervioAntebrazoIzquierdo,
    nervioRadialIzquierdo = nervioRadialIzquierdo,
    nervioAxilarIzquierdo = nervioAxilarIzquierdo
)
